name: Climate App - PROD Deploy

on:
  push:
    branches:
      - main
    ##paths:
      ##- "apps/climate-change/prd/**"
    # Allow manually trigger
  workflow_dispatch:
    inputs:
      job_to_run:
        description: 'Which job to run'
        required: true
        type: choice
        options:
          - deploy-prd

jobs:
  deploy-prd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Static Web App (PROD)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_CLIMATE_PROD_TOKEN }}
          action: upload
          app_location: apps/climate_change/prd/
          output_location: ""
